"use client";

import { FormEvent, useState, useTransition } from "react";
import { Loader2, Save } from "lucide-react";
import { useRouter } from "next/navigation";
import { guardarTurmaServer } from "@/features/academic-management/actions";

type Curso = { id: number; nomeCurso: string };
type Turma = { id: number; idCurso: number; nomeTurma: string; anoCurricular: number; periodo: string };
const periodos = ["Manhã", "Tarde", "Pós-laboral"];

export function FormularioTurmaClient({ cursos, turmas }: { cursos: Curso[]; turmas: Turma[] }) {
  const router = useRouter(); const [isPending, startTransition] = useTransition(); const [idTurma, setIdTurma] = useState(""); const [idCurso, setIdCurso] = useState(String(cursos[0]?.id || "")); const [nomeTurma, setNomeTurma] = useState(""); const [anoCurricular, setAnoCurricular] = useState("1"); const [periodo, setPeriodo] = useState(periodos[0]); const [mensagem, setMensagem] = useState<string | null>(null);
  const selecionar = (valor: string) => { setIdTurma(valor); const turma = turmas.find((item) => item.id === Number(valor)); setIdCurso(turma ? String(turma.idCurso) : String(cursos[0]?.id || "")); setNomeTurma(turma?.nomeTurma || ""); setAnoCurricular(String(turma?.anoCurricular || 1)); setPeriodo(turma?.periodo || periodos[0]); };
  const guardar = (evento: FormEvent<HTMLFormElement>) => { evento.preventDefault(); startTransition(async () => { const resultado = await guardarTurmaServer(idTurma || null, { idCurso, nomeTurma, anoCurricular, periodo }); setMensagem(resultado.success ? "Turma guardada com sucesso." : resultado.error || "Não foi possível guardar a turma."); if (resultado.success) { selecionar(""); router.refresh(); } }); };
  return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-5"><h3 className="text-lg font-bold text-slate-800">Gerir turmas</h3><p className="text-sm text-slate-500">Crie ou atualize turmas dos cursos sob a sua coordenação.</p></div>{mensagem && <p role="status" className="mb-4 rounded-xl bg-slate-50 px-4 py-3 text-sm text-slate-700">{mensagem}</p>}<form onSubmit={guardar} className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-5"><label className="space-y-2 text-sm font-semibold text-slate-700"><span>Turma a editar</span><select value={idTurma} onChange={(evento) => selecionar(evento.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">Nova turma</option>{turmas.map((item) => <option key={item.id} value={item.id}>{item.nomeTurma}</option>)}</select></label><label className="space-y-2 text-sm font-semibold text-slate-700"><span>Curso</span><select value={idCurso} onChange={(evento) => setIdCurso(evento.target.value)} required className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">Selecionar</option>{cursos.map((item) => <option key={item.id} value={item.id}>{item.nomeCurso}</option>)}</select></label><label className="space-y-2 text-sm font-semibold text-slate-700"><span>Nome da turma</span><input value={nomeTurma} onChange={(evento) => setNomeTurma(evento.target.value)} maxLength={50} required className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /></label><label className="space-y-2 text-sm font-semibold text-slate-700"><span>Ano curricular</span><input type="number" value={anoCurricular} onChange={(evento) => setAnoCurricular(evento.target.value)} min="1" max="10" required className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /></label><label className="space-y-2 text-sm font-semibold text-slate-700"><span>Período</span><select value={periodo} onChange={(evento) => setPeriodo(evento.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm">{periodos.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><div className="md:col-span-2 xl:col-span-5 flex justify-end"><button type="submit" disabled={isPending || cursos.length === 0} className="inline-flex items-center gap-2 rounded-full bg-brand-blue px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}{isPending ? "A guardar..." : "Guardar turma"}</button></div></form></section>;
}