"use client";

import { FormEvent, useState, useTransition } from "react";
import { Loader2, Save } from "lucide-react";
import { useRouter } from "next/navigation";
import { guardarDisciplinaServer } from "@/features/academic-management/actions";

type Curso = { id: number; nomeCurso: string };
type Disciplina = { id: number; idCurso: number; nomeDisciplina: string; semestre: number };

export function FormularioDisciplinaClient({ cursos, disciplinas }: { cursos: Curso[]; disciplinas: Disciplina[] }) {
  const router = useRouter(); const [isPending, startTransition] = useTransition(); const [idDisciplina, setIdDisciplina] = useState(""); const [idCurso, setIdCurso] = useState(String(cursos[0]?.id || "")); const [nomeDisciplina, setNomeDisciplina] = useState(""); const [semestre, setSemestre] = useState("1"); const [mensagem, setMensagem] = useState<string | null>(null);
  const selecionar = (valor: string) => { setIdDisciplina(valor); const disciplina = disciplinas.find((item) => item.id === Number(valor)); setIdCurso(disciplina ? String(disciplina.idCurso) : String(cursos[0]?.id || "")); setNomeDisciplina(disciplina?.nomeDisciplina || ""); setSemestre(String(disciplina?.semestre || 1)); };
  const guardar = (evento: FormEvent<HTMLFormElement>) => { evento.preventDefault(); startTransition(async () => { const resultado = await guardarDisciplinaServer(idDisciplina || null, { idCurso, nomeDisciplina, semestre }); setMensagem(resultado.success ? "Disciplina guardada com sucesso." : resultado.error || "Não foi possível guardar a disciplina."); if (resultado.success) { selecionar(""); router.refresh(); } }); };
  return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-5"><h3 className="text-lg font-bold text-slate-800">Gerir disciplinas</h3><p className="text-sm text-slate-500">Crie ou atualize disciplinas apenas nos cursos sob a sua coordenação.</p></div>{mensagem && <p role="status" className="mb-4 rounded-xl bg-slate-50 px-4 py-3 text-sm text-slate-700">{mensagem}</p>}<form onSubmit={guardar} className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4"><label className="space-y-2 text-sm font-semibold text-slate-700"><span>Disciplina a editar</span><select value={idDisciplina} onChange={(evento) => selecionar(evento.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">Nova disciplina</option>{disciplinas.map((item) => <option key={item.id} value={item.id}>{item.nomeDisciplina}</option>)}</select></label><label className="space-y-2 text-sm font-semibold text-slate-700"><span>Curso</span><select value={idCurso} onChange={(evento) => setIdCurso(evento.target.value)} required className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">Selecionar</option>{cursos.map((item) => <option key={item.id} value={item.id}>{item.nomeCurso}</option>)}</select></label><label className="space-y-2 text-sm font-semibold text-slate-700"><span>Nome da disciplina</span><input value={nomeDisciplina} onChange={(evento) => setNomeDisciplina(evento.target.value)} maxLength={150} required className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /></label><label className="space-y-2 text-sm font-semibold text-slate-700"><span>Semestre</span><input type="number" value={semestre} onChange={(evento) => setSemestre(evento.target.value)} min="1" max="20" required className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /></label><div className="md:col-span-2 xl:col-span-4 flex justify-end"><button type="submit" disabled={isPending || cursos.length === 0} className="inline-flex items-center gap-2 rounded-full bg-brand-blue px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}{isPending ? "A guardar..." : "Guardar disciplina"}</button></div></form></section>;
}