"use client";

import { useState, useTransition } from "react";
import { Loader2, Send } from "lucide-react";
import { useRouter } from "next/navigation";
import { iniciarTentativaAvaliacaoServer, submeterTentativaAvaliacaoServer } from "@/features/assessments/actions/tentativas.actions";

type Alternativa = { id: number; textoAlternativa: string };
type Questao = { id: number; enunciado: string; tipoQuestao: string; alternativas: Alternativa[] };
type Avaliacao = { id: number; titulo: string; dataInicio: string; dataFim: string; duracaoMinutos: number; notaMaxima: string; questoes: Questao[] };
type Tentativa = { id: number; statusTentativa: string; notaObtida?: string | null; submetidoEm?: string | null } | null;

export function ResolverAvaliacaoClient({ avaliacao, tentativa }: { avaliacao: Avaliacao; tentativa: Tentativa }) {
  const router = useRouter(); const [isPending, startTransition] = useTransition(); const [respostas, setRespostas] = useState<Record<number, string>>({}); const [mensagem, setMensagem] = useState<string | null>(null);
  const iniciar = () => startTransition(async () => { const resultado = await iniciarTentativaAvaliacaoServer(avaliacao.id); setMensagem(resultado.success ? null : resultado.error || "Não foi possível iniciar."); if (resultado.success) router.refresh(); });
  const submeter = () => { if (!tentativa) return; startTransition(async () => { const resultado = await submeterTentativaAvaliacaoServer(tentativa.id, avaliacao.questoes.map((questao) => questao.tipoQuestao === "desenvolvimento" ? { idQuestao: questao.id, textoResposta: respostas[questao.id] || "" } : { idQuestao: questao.id, idAlternativaEscolhida: respostas[questao.id] || "" })); setMensagem(resultado.success ? "Avaliação submetida com sucesso." : resultado.error || "Não foi possível submeter."); if (resultado.success) router.refresh(); }); };
  if (tentativa?.statusTentativa === "submetida") return <div className="rounded-3xl border border-emerald-200 bg-emerald-50 p-8 text-center"><h2 className="text-xl font-bold text-emerald-800">Avaliação submetida</h2><p className="mt-2 text-sm text-emerald-700">A sua submissão foi registada. {tentativa.notaObtida ? `Nota automática: ${tentativa.notaObtida}.` : "A correção será concluída pelo docente."}</p></div>;
  if (!tentativa) return <div className="rounded-3xl border border-slate-200 bg-white p-8 text-center shadow-sm"><h2 className="text-xl font-bold text-slate-800">{avaliacao.titulo}</h2><p className="mt-2 text-sm text-slate-500">{avaliacao.questoes.length} questão(ões) · {avaliacao.duracaoMinutos} minutos · nota máxima {avaliacao.notaMaxima}</p>{mensagem && <p role="status" className="mt-4 text-sm font-semibold text-red-700">{mensagem}</p>}<button type="button" onClick={iniciar} disabled={isPending} className="mt-6 inline-flex items-center gap-2 rounded-full bg-brand-blue px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{isPending && <Loader2 className="h-4 w-4 animate-spin" />}Iniciar avaliação</button></div>;
  return <div className="space-y-5"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-bold text-slate-800">{avaliacao.titulo}</h2><p className="mt-1 text-sm text-slate-500">Responda todas as questões e submeta antes do prazo.</p>{mensagem && <p role="status" className="mt-3 rounded-xl bg-slate-50 px-3 py-2 text-sm text-slate-700">{mensagem}</p>}</div>{avaliacao.questoes.map((questao, indice) => <section key={questao.id} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="font-bold text-slate-800">{indice + 1}. {questao.enunciado}</h3>{questao.tipoQuestao === "desenvolvimento" ? <textarea value={respostas[questao.id] || ""} onChange={(evento) => setRespostas((estado) => ({ ...estado, [questao.id]: evento.target.value }))} maxLength={3000} rows={6} className="mt-4 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" placeholder="Escreva a sua resposta" /> : <div className="mt-4 space-y-2">{questao.alternativas.map((alternativa) => <label key={alternativa.id} className="flex cursor-pointer items-start gap-3 rounded-xl border border-slate-200 p-3 text-sm text-slate-700"><input type="radio" name={`questao-${questao.id}`} value={alternativa.id} checked={respostas[questao.id] === String(alternativa.id)} onChange={() => setRespostas((estado) => ({ ...estado, [questao.id]: String(alternativa.id) }))} className="mt-0.5" />{alternativa.textoAlternativa}</label>)}</div>}</section>)}<div className="flex justify-end"><button type="button" onClick={submeter} disabled={isPending} className="inline-flex items-center gap-2 rounded-full bg-brand-blue px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}Submeter avaliação</button></div></div>;
}